In [ ]:
'''
What is NumPy?
NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant.
It is an open source project and you can use it freely.
NumPy stands for Numerical Python.

Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists,
so processes can access and manipulate them very efficiently.
This behavior is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists.
Also it is optimized to work with latest CPU architectures.

Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python,
but most of the parts that require fast computation are written in C or C++.

'''

Array:


In [ ]:
'''
    Collection of homogenous data
    indexed and oredered
    allows duplicate values
    Mutable
'''

In [15]:
import numpy as np

In [ ]:
arr = np.array(11)
print(arr)
print(type(arr))  # <class 'numpy.ndarray'>
print(arr.dtype)  # int64
print(arr.shape)
print(arr.ndim)

arr = np.array(11.0)
print(arr)
print(type(arr))  
print(arr.dtype)  # float64
print(arr.ndim)

11
<class 'numpy.ndarray'>
int64
()
0
11.0
<class 'numpy.ndarray'>
float64
0


1D Array

In [ ]:
arr=np.array([1,2,3,4,5,'Lucy'])
print(arr)
print(type(arr))
print((arr).dtype)  # <U21  # similar to str
print((arr).ndim)  # 1
print(arr.shape)  # (6,)   # tuple()

['1' '2' '3' '4' '5' 'Lucy']
<class 'numpy.ndarray'>
<U21
1
(6,)


2D Array

In [25]:
arr=np.array([
              [1,2,3,4,5],
              [6,7,8,9,1]
             ])
print(arr)
print(type(arr))
print((arr).dtype)
print((arr).ndim)  # 2
print((arr).shape)  # (2, 5)

[[1 2 3 4 5]
 [6 7 8 9 1]]
<class 'numpy.ndarray'>
int64
2
(2, 5)


In [4]:
arr = np.array([
                [1,2,3],
                [4,5,6],
                [6,7,8]
               ])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)
2


In [5]:
arr = np.array([
                [1,2,3,4,5,6],
                [6,5,4,3,2,1]
               ])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
(2, 6)
2


In [6]:
arr = np.array([
                [1,2,3],
                [6,5,4],
                [8,7,5],
                [3,4,5],
                [5,6,8],
                [3,4,7]
               ])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [6 5 4]
 [8 7 5]
 [3 4 5]
 [5 6 8]
 [3 4 7]]
(6, 3)
2


3D Array

In [7]:
arr=np.array([
              [
                [1,2],
                [3,4]
              ],
              [
                [4,3],
                [3,2]
              ]
             ])
print(arr)
print(type(arr))
print((arr).dtype)
print((arr).ndim)  # 3
print((arr).shape)  # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[4 3]
  [3 2]]]
<class 'numpy.ndarray'>
int32
3
(2, 2, 2)


In [8]:
arr=np.array([

            [

                [1,2,3,4,10],

                [6,7,8,9,20],

                [22,11,23,77,33],

                [10,66,22,11,56]

            ],

            [

                [10,11,12,13,30],

                [14,15,16,17,40],

                [18,19,20,21,50],

                [22,23,24,25,60]

            ] ,

            [

                [18,19,20,21,50],

                [22,23,24,25,60],

                [26,27,28,29,70],

                [30,31,32,33,80]

            ],

          ])

print(arr)
print((arr.shape))

[[[ 1  2  3  4 10]
  [ 6  7  8  9 20]
  [22 11 23 77 33]
  [10 66 22 11 56]]

 [[10 11 12 13 30]
  [14 15 16 17 40]
  [18 19 20 21 50]
  [22 23 24 25 60]]

 [[18 19 20 21 50]
  [22 23 24 25 60]
  [26 27 28 29 70]
  [30 31 32 33 80]]]
(3, 4, 5)


Higher Dimensional Arrays

In [23]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.

arr = np.array([1,2,3],ndmin =32)
print(arr.shape)
print(arr.ndim,arr)

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3)
32 [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
