In [ ]:
'''

What are ufuncs?

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.


Why use ufuncs?

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where : boolean array or condition defining where the operations should take place.

dtype : defining the return type of elements.

out : output array where the return value should be copied.

 

What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

'''

In [2]:
import numpy as np

1-Simple Arithmatic

In [4]:
# add()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,12,13,14,15])
arr3 = np.array([4,5,6,7,8])
arr = np.add(arr1,arr2,arr3)
print(arr)

[12 14 16 18 20]


In [15]:
# substract()
arr = np.array([1,2,3,4,5])
arr1 = np.array([11,12,13,14,15])
arr2 = np.subtract(arr1,arr)
print(arr2)

[10 10 10 10 10]


In [16]:
# multiply()
arr = np.array([1,2,3,4,5])
arr1 = np.array([11,12,13,14,15])
arr2 = np.multiply(arr,arr1)
print(arr2)

[11 24 39 56 75]


In [17]:
# divide()
arr = np.array([1,2,3,4,5])
arr1 = np.array([11,12,13,14,15])
arr2 = np.divide(arr,arr1)
print(arr2)

[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]


In [21]:
# mod(), remainder()
arr = np.array([1,2,3,4,5])
arr1 = np.array([11,12,13,14,15])
arr2 = np.mod(arr1,arr)
print(arr2)

arr2 = np.remainder(arr1,arr)
print(arr2)

[0 0 1 2 0]
[0 0 1 2 0]


In [22]:
# divmod(), Quotient-Remainder
arr = np.array([1,2,3,4,5])
arr1 = np.array([11,12,13,14,15])
arr2 = np.divmod(arr1,arr)
print(arr2)

(array([11,  6,  4,  3,  3]), array([0, 0, 1, 2, 0]))


In [23]:
# power()
arr = np.array([1,2,3,4,5])
arr1 = np.array([11,12,13,14,15])
arr2 = np.power(arr1,arr)
print(arr2)

[    11    144   2197  38416 759375]


In [25]:
# absolute()
arr = np.array([1,2,-3,4,-5])
arr2 = np.absolute(arr)
print(arr2)

[1 2 3 4 5]


2-Rounding Decimal

In [5]:
# Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

# No difference in behavior in NumPy: np.trunc() and np.fix() produce the same results.
# Both truncate towards zero, meaning they don’t round up or down.


print('------trunc()------')
arr = np.trunc([3.233,-3.934])
print(arr)

print('-------fix()-------')
arr = np.fix([3.999999,-3.456565])
print(arr)

------trunc()------
[ 3. -3.]
-------fix()-------
[ 3. -3.]


In [9]:
arr = np.fix([3.999999,-3.456565])
print(arr)

[ 3. -3.]


In [10]:
# around()

arr = np.around(3.1234439,6)
print(arr)

arr = np.around(3.1234433,3)
print(arr)

3.123444
3.123


In [7]:
# floor() : lowest closest integer

arr = np.floor([3.1234433,-3.8])
print(arr)

[ 3. -4.]


In [29]:
# ceil() : highest closest integer

arr = np.ceil([3.1234433,3])
print(arr)

[4. 3.]


3-Log

In [13]:
arr = np.arange(1,10)
print(arr)

print('------------log2()-------------')
print(np.log2(arr))

print('------------log10()------------')
print(np.log10(arr))

print('-------------log()-------------')
print(np.log(arr))

[1 2 3 4 5 6 7 8 9]
------------log2()-------------
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
------------log10()------------
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
-------------log()-------------
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


4-Summation

In [ ]:
'''
Summations:

Addition is done between two arguments whereas summation happens over n elements.

'''

In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.sum([arr1,arr2])
print(arr)

21


In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.sum([arr1,arr2],axis=1)
print(arr)

[ 6 15]


In [ ]:
'''

Cummulative Sum:

Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

'''

In [32]:
# cumsum()
arr1 = np.array([1,2,3,4,5])
arr = np.cumsum(arr1)
print(arr)

[ 1  3  6 10 15]


5-Product

In [34]:
# prod()
arr1 = np.array([1,2,3,4,5])
arr = np.prod(arr1)
print(arr)

120


In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.prod([arr1,arr2])
print(arr)

720


In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.prod([arr1,arr2],axis=1)
print(arr)

[  6 120]


In [ ]:
'''

Cummulative Product:

Cummulative product means partially multiplying the elements in array.

E.g. The partial multiplication of [1, 2, 3, 4] would be [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24].

Perfom partial product with the cumprod() function.

'''

In [36]:
# cumprod()
arr1 = np.array([1,2,3,4,5])
arr = np.cumprod(arr1)
print(arr)

[  1   2   6  24 120]


6-Difference

In [ ]:
'''

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

'''

In [37]:
# diff()
arr = np.array([10,20,15,30])   # [20-10=10, 15-20=-5, 30-15=15]
arr = np.diff(arr)
print(arr)

[10 -5 15]


In [17]:
arr = np.array([10,20,15,30])   # [20-10=10, 15-20=-5, 30-15=15] = [-5-10=-15, 15-(-5)=20]
arr = np.diff(arr,n=2)
print(arr)

[-15  20]


7-LCM

In [12]:
# lcm()
a = 4
b = 6
x = np.lcm(a,b)
print(x)

12


In [40]:
a = 5
b = 10
x = np.lcm(a,b)
print(x)

10


In [41]:
arr = np.array([3,6,9])
x = np.lcm.reduce(arr)
print(x)

18


8-GCD

In [42]:
# gcd()
# Greatest Comman Devisor (HCF - Highest Comman Factor)
a = 6
b = 9
x = np.gcd(a,b)
print(x)

3


In [43]:
arr = np.array([3,6,9,36])
x = np.gcd.reduce(arr)
print(x)

3


9-Trigonometry

In [34]:
# NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

print(np.sin(np.pi/2))

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]


In [ ]:
# By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.
# Note: radians values are pi/180 * degree_values.

# Convert Degrees Into Radians

arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [31]:
# Radians to Degrees

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [28]:
# Finding Angles:

# Finding angles from values of sine, cos, tan.
# E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

# NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

x = np.arcsin(1.0)
print(x)

1.5707963267948966


In [27]:
# Hypotenues:
# Finding hypotenues using pythagoras theorem in NumPy.

# NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


10-Hyperbolic Functions

In [38]:
# NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [39]:
# Finding Angles
# Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

# Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

x = np.arcsinh(1.0)
print(x)

0.881373587019543


User Defined Numpy Functions

In [41]:
def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd,2,1)

print(myadd([1,2,3,4],[9,8,7,6]))
print(type(myadd))

[10 10 10 10]
<class 'numpy.ufunc'>
