Slicing:

2D-arrays slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [77,44,66,83],
    [45,76,34,34]
])
print(arr[1])
print(arr[1][-3])
print(arr[1][2])
print(arr[1][1::2])
print(arr[-1])
print(arr[-1][-2:])

[45 76 34 34]
76
34
[76 34]
[45 76 34 34]
[34 34]


In [3]:
arr = np.array([
    [11,22,33,44],
    [21,31,41,51],
    [55,66,77,88]
])

'''
[[11 22]
 [21 31]]
'''
print(arr[:2,:2])  # [start_row_index:end_row_index,start_column_index:end_column_index]

'''
[[22 33]
 [66 77]]
'''
print(arr[::2,1:3])

'''
[[21 51]
 [55 88]]
'''
print(arr[1:,::3])

[[11 22]
 [21 31]]
[[22 33]
 [66 77]]
[[21 51]
 [55 88]]


In [4]:
arr = np.array([
    [11,22,33],
    [21,31,41],
    [55,66,77]
])
print(arr[1:2,::2])  #[[21 41]]

print(arr[1,::2])

[[21 41]]
[21 41]


In [5]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr2d[[0,2],[1,2]])  # [2,9]  # (0,1):2 (2,2):9

print(arr2d[[0,2],[0,1]])  # [1 8]

print(arr2d[[0,1,2],[0,1,2]])  # [1 5 9]

print(arr2d[[0,2],[0,2]]) # [1 9]

print(arr2d[[0,1],[2,0]])  # [3 4]

print(arr2d[[0,2],[2,0]])  # [3 7]

[2 9]
[1 8]
[1 5 9]
[1 9]
[3 4]
[3 7]


3D-array slicing

In [30]:
arr_3d = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]   
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]

])

print(arr_3d.shape)

(3, 3, 3)


In [ ]:
# slicing 2D arrays from 3D array
print(arr_3d[0])
print(arr_3d[-2])
print(arr_3d[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [ ]:
# slicing 1D arrays from 3D array
print(arr_3d[0][-1])
print(arr_3d[0][1])
print(arr_3d[0][0])

[7 8 9]
[4 5 6]
[1 2 3]


In [31]:
# slicing elements arrays from 3D array
print(arr_3d[0][0][0])
print(arr_3d[0][0][-1])
print(arr_3d[0][0][1])

1
3
2


In [10]:
'''
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]
'''

print(arr_3d[:1,:1,::2])  # [[[1 3]]]


'''
[
 [ [1,3] ]
 [ [10,12] ]
]
'''
print(arr_3d[:2,0:1,::2])


'''
[[1 3]
 [7 9]]
'''
print(arr_3d[0,::2,::2])

[[[1 3]]]
[[[ 1  3]]

 [[10 12]]]
[[1 3]
 [7 9]]


In [11]:
print(arr_3d[[0,1,2],[0,1,2],[1,2,0]])   # [2 15 25]

[ 2 15 25]


In [12]:
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]
'''

print(arr_3d[:1,:1,::2])  # [[[1 3]]]


'''
[
 [ [1,3] ]
 [ [10,12] ]
]
'''
print(arr_3d[:2,0:1,::2])


'''
[[1 3]
 [7 9]]
'''
print(arr_3d[0,::2,::2])

[[[1 3]]]
[[[ 1  3]]

 [[10 12]]]
[[1 3]
 [7 9]]


In [13]:
print(arr_3d[[0,1,2],[0,2,2],[1,1,2]])  # [ 2 17 27]

[ 2 17 27]


In [2]:
import numpy as np
arr = np.array([
       [[1, 2, 3], [4, 5, 6]],
       [[7, 8, 9], [10, 11, 12]],
       [[13, 14, 15], [16, 17, 18]]
   ])
arr[:,:,1:2]

array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]])

ALPHA-2025

In [24]:
arr = np.array([
    [1,2,3,4],
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44]
])

print('--------------')
print(arr[::,::-1])

print('--------------')
print(arr[::-1,::])

print('--------------')
print(arr[::-1,::-1])

print('--------------')
print(arr[[0,1],[1,3]])

print('--------------')
print(arr[[0,3],[0,3]])

print('--------------')
print(arr[[0,2,4],[0,3,1]])

--------------
[[ 4  3  2  1]
 [14 13 12 11]
 [24 23 22 21]
 [34 33 32 31]
 [44 43 42 41]]
--------------
[[41 42 43 44]
 [31 32 33 34]
 [21 22 23 24]
 [11 12 13 14]
 [ 1  2  3  4]]
--------------
[[44 43 42 41]
 [34 33 32 31]
 [24 23 22 21]
 [14 13 12 11]
 [ 4  3  2  1]]
--------------
[ 2 14]
--------------
[ 1 34]
--------------
[ 1 24 42]


In [26]:
arr = np.array([

               [

                  [1,2,3],

                  [11,12,13],

                  [101,102,103],

              ],

              [

                  [21,22,23],

                  [31,32,33],

                  [111,112,113],

              ],

               [

                  [41,42,43],

                  [41,42,43],

                  [121,122,123],

               ]

            ])

In [55]:
print('------------')
print(arr[0][0])

print('------------')
print(arr[:,:1])

print('------------')
a = arr[:,:1]
print("Shape of 'a':",a.shape)

print('------------')
print(arr[::2,-1])

print('------------')
print(arr[::2,-1,::2])

print('------------')
print(arr[::2,::2,::2])

------------
[1 2 3]
------------
[[[ 1  2  3]]

 [[21 22 23]]

 [[41 42 43]]]
------------
Shape of 'a': (3, 1, 3)
------------
[[101 102 103]
 [121 122 123]]
------------
[[101 103]
 [121 123]]
------------
[[[  1   3]
  [101 103]]

 [[ 41  43]
  [121 123]]]


In [59]:
print('------------')
print(arr[::-1,::-1,::-1])

print('------------')
print(arr[[0,1,2],[0,1,2],[0,2,1]])

------------
[[[123 122 121]
  [ 43  42  41]
  [ 43  42  41]]

 [[113 112 111]
  [ 33  32  31]
  [ 23  22  21]]

 [[103 102 101]
  [ 13  12  11]
  [  3   2   1]]]
------------
[  1  33 122]
