In [ ]:
'''

The Difference Between Copy and View:

The main difference between a copy and a view of an array is that the copy is a new array, 

and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, 

and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, 

and any changes made to the original array will affect the view.

'''

In [1]:
import numpy as np

In [2]:
arr_original = np.array([1,2,3,4])
arr_copy = arr_original.copy()
print(arr_original)
print(arr_copy)

[1 2 3 4]
[1 2 3 4]


In [5]:
arr_original[0] = 99
print(arr_original)
print(arr_copy)

[99  2  3  4]
[1 2 3 4]


In [ ]:
'''
How does it work?

The object (arr_original) has two parts:
The Python object metadata (which includes ID, shape, dtype, etc.).
The data buffer (actual array values stored in memory).
When you create a view (arr_view = arr_original.view()):
A new Python object (arr_view) is created with a different id(arr_view).
But the data buffer (memory location of the elements) is shared with arr_original.
This means modifying elements in arr_view also modifies arr_original, since both point to the same underlying data.

'''

In [22]:
arr_original = np.array([1,2,3,4])
arr_view = arr_original.view()
print(arr_original, id(arr_original))
print(arr_view, id(arr_view))

print(arr_original == arr_copy)

[1 2 3 4] 1802586377168
[1 2 3 4] 1802586383504
[ True  True  True  True]


In [7]:
arr_original[0] = 100
print(arr_original)
print(arr_view)

[100   2   3   4]
[100   2   3   4]


In [8]:
arr_original = np.array([1,2,3])
arr_test = arr_original
print(arr_original)
print(arr_test)

[1 2 3]
[1 2 3]


In [9]:
arr_original[0] = 99
print(arr_original)
print(arr_test)

[99  2  3]
[99  2  3]


In [5]:
# The copy returns None.
# The view returns the original array.

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
