In [3]:
import numpy as np

2D array iteration

In [2]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

l =arr.shape
l

(3, 3)

In [3]:
for x in range(l[0]):
    print(arr[x])

[1 2 3]
[4 5 6]
[7 8 9]


In [4]:
for y in range(l[0]):
    for x in range(l[1]):
        print(arr[y][x])

1
2
3
4
5
6
7
8
9


3D array iteration

In [7]:
arr = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ],
])
l = arr.shape
print(l)

(3, 3, 3)


In [8]:
for x in range(l[2]):
    print(arr[x])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [9]:
for x in range(l[0]):
    for y in range(l[1]):
        print(arr[x][y])

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]
[16 17 18]
[19 20 21]
[22 23 24]
[25 26 27]


In [10]:
for x in range(l[0]):
    for y in range(l[1]):
        for z in range(l[2]):
            print(arr[x][y][z])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [11]:
for i in arr[0][0]:
    print(i)
    

1
2
3


Alpha

In [8]:
arr = np.array([
    [1,2,3,4,5],
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35]
])

In [21]:
sum = 0
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        sum+=arr[i][j]
print('Sum =',sum)

Sum = 360


In [27]:

for i in range(arr.shape[0]):
    sum = 0
    for j in arr[i]:
        sum+=j
    print('Sum =',sum)

Sum = 15
Sum = 65
Sum = 115
Sum = 165


In [32]:
arr = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [11,12,13],
        [14,15,16],
        [17,18,19]
    ],
    [
        [21,22,23],
        [24,25,26],
        [27,28,29]
    ]
])

In [ ]:
# extracting single elements from a 3D array
for z in range(arr.shape[0]):
    for y in range(arr.shape[1]):
        for x in range(arr.shape[2]):
            print(arr[z][y][x], end=' ')

1 2 3 4 5 6 7 8 9 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26 27 28 29 

In [37]:
for x in np.nditer(arr):
    print(x, end = ' ')

1 2 3 4 5 6 7 8 9 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26 27 28 29 

In [40]:
for x,y in np.ndenumerate(arr):
    print(x,y, end = ' , ')

(0, 0, 0) 1 , (0, 0, 1) 2 , (0, 0, 2) 3 , (0, 1, 0) 4 , (0, 1, 1) 5 , (0, 1, 2) 6 , (0, 2, 0) 7 , (0, 2, 1) 8 , (0, 2, 2) 9 , (1, 0, 0) 11 , (1, 0, 1) 12 , (1, 0, 2) 13 , (1, 1, 0) 14 , (1, 1, 1) 15 , (1, 1, 2) 16 , (1, 2, 0) 17 , (1, 2, 1) 18 , (1, 2, 2) 19 , (2, 0, 0) 21 , (2, 0, 1) 22 , (2, 0, 2) 23 , (2, 1, 0) 24 , (2, 1, 1) 25 , (2, 1, 2) 26 , (2, 2, 0) 27 , (2, 2, 1) 28 , (2, 2, 2) 29 , 

In [41]:
# 1- Sum of All Elements in a 2D Array

arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])

# ExpectedOutput: Sum:45
sum = 0
for i in np.nditer(arr):
    sum+=i
print(f'Sum:{sum}')

Sum:45


In [42]:
# 2- Element-wise Multiplication of Two 2D Arrays

arr1=np.array([[1,2,3],
[4,5,6]])

arr2=np.array([[2,3,4],
[5,6,7]])

'''
ExpectedOutput:
[[2612]
[203042]]
'''
print(arr1*arr2)


[[ 2  6 12]
 [20 30 42]]


In [43]:
# 3️ Element-wise Division(Avoid DividebyZeroError)

arr1=np.array([[10,20,30],
[40,50,60]])

arr2=np.array([[2,0,5],
[4,10,0]])#Containszero

 
'''
Expected Output(handled division byzerobyreplacingwith1):

[[5.010.06.0]
[10.05.060.0]]
'''

print(arr1/arr2)

[[ 5. inf  6.]
 [10.  5. inf]]


C:\Users\pruth\AppData\Local\Temp\ipykernel_7460\1073529090.py:17: RuntimeWarning: divide by zero encountered in divide
  print(arr1/arr2)


In [61]:
# 4️- Row-wise and Column-wise Sum

arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])

'''
Expected Output:
Rowsums:[6,15,24]
Columnsums:[12,15,18]
'''
row = []
for i in range(arr.shape[0]):
    sum = 0
    for j in arr[i]:
        sum+=j
    row.append(int(sum))
print(f'Rowsums:{row}')

Rowsums:[6, 15, 24]


In [4]:
# 4- Row-wise and Column-wise Sum
arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])
row=np.sum(arr,axis=1)
Column=np.sum(arr,axis=0)
print(f"row of row:",row)
print(f"Column of Column:",Column)


row of row: [ 6 15 24]
Column of Column: [12 15 18]


In [60]:
# 5️-Sum of All Elements in a 3D Array

arr=np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])

# Expected Output: Sum:36

sum = 0
for i in np.nditer(arr):
    sum+=i
print(f'Sum:{sum}')

Sum:36


In [ ]:
# 6️-Element-wise Multiplication of Two 3DArrays 

arr1=np.array([[[1,2],[3,4]],
[[5,6],[7,8]]])

arr2=np.array([[[2,3],[4,5]],
[[6,7],[8,9]]])

'''
Expected Output:
[[[ 2  6]
  [12 20]]

 [[30 42]
  [56 72]]]
'''
print(arr1*arr2)

[[[ 2  6]
  [12 20]]

 [[30 42]
  [56 72]]]


In [ ]:
# 7️- Find the Average of a 3DArray

arr=np.array([[[1,2,3],
[4,5,6]],
[[7,8,9],
[10,11,12]]])

# Expected Output: Average:6.5

total,count = 0,0
for i in np.nditer(arr):
    total+=i
    count+=1

avg = total/count
print(f'Average:{avg}')

Average:6.5
