In [1]:
import numpy as np

concatenate()

In [ ]:
'''

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, 

along with the axis. If axis is not explicitly passed, it is taken as 0.

'''

In [3]:
# 1D Join
a1 = np.array([1,2,3])
a2 = np.array([4,5])
a3 = np.concatenate((a1,a2))  # tuple  # only pass arguments in form of tuple or list 
a3

array([1, 2, 3, 4, 5])

In [4]:
a1 = np.array([1,2,3])
a2 = np.array([4,5])
a3 = np.array([100])
a3 = np.concatenate([a1,a3,a2])  # list
a3

array([  1,   2,   3, 100,   4,   5])

In [6]:
# 2D Join
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
a3 = np.concatenate((a1,a2))   # axis=0 by default it adds row wise
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
a3 = np.concatenate((a1,a2),axis=1)   # axis=1 it adds column wise
a3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [10]:
# 3D Join

a1 = np.array([
                [
                    [1,2,3],
                    [4,5,6]
                ],
                [
                    [7,8,9],
                    [10,11,12]
                ]
               ])

a2 = np.array([
                [
                    [13,14,15],
                    [16,17,18]
                ],
                [
                    [19,20,21],
                    [22,23,24]
                ]
               ])

print('------with axis=0 (default)------')
a3 = np.concatenate((a1,a2))
print(a3)

print('------with axis=1------')
a4 = np.concatenate((a1,a2),axis=1)
print(a4)

print('------with axis=2------')
a5 = np.concatenate((a1,a2),axis=2)
print(a5)

------with axis=0 (default)------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
------with axis=1------
[[[ 1  2  3]
  [ 4  5  6]
  [13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]
  [19 20 21]
  [22 23 24]]]
------with axis=2------
[[[ 1  2  3 13 14 15]
  [ 4  5  6 16 17 18]]

 [[ 7  8  9 19 20 21]
  [10 11 12 22 23 24]]]


stack()

In [ ]:
'''

Joining Arrays Using Stack Functions:

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which

would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack()

method along with the axis. If axis is not explicitly passed it is taken as 0.

'''

In [20]:
# Stacking along with the row
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_c = np.concatenate((arr1,arr2))
print(arr_c)

arr = np.stack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# arr_c = np.concatenate((arr1,arr2), axis=1)  # AxisError: axis 1 is out of bounds for array of dimension 1
# print(arr_c)

arr = np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Stacking along the row
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Stacking along the column
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking along the height(depth)
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# stack joins arrays along a new axis (dimension), while concatenate joins arrays along an existing axis.

split()

In [ ]:
'''

Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

'''

In [ ]:
# The return value is a list containing three arrays.
arr = np.array([1,2,3,4,5,6,7,8,9])
arr1 = np.array_split(arr,3)
print(arr1)

arr1 = np.array_split(arr,4)
print(arr1)

arr1 = np.array_split(arr,9)
print(arr1)

arr1 = np.array_split(arr,12)
print(arr1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [10]:
arr1 = np.array_split(arr,3)
print(arr1[0])
print(arr1[1])
print(arr1[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
# 2D array splitting

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr1 = np.array_split(arr,3)
print(arr1)

print(arr1[0])
print(arr1[1])
print(arr1[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [13]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr1 = np.array_split(arr,2,axis=1)   # column wise
print(arr1)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [5]:
arr1 = np.array_split(arr,3,axis=1)
print(arr1)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
arr1 = np.hsplit(arr,3)  # operates horizonatally
print(arr1)


print(arr1[0])

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


In [8]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr1 = np.dsplit(arr,3)
print(arr1)


print(arr1[0])

[array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]]]), array([[[ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18]]])]
[[[ 1]
  [ 4]
  [ 7]]

 [[10]
  [13]
  [16]]]


In [ ]:
# Note: We also have the method split() available but it will not adjust the elements when elements are less
# in source array for splitting like in example above, array_split() worked properly but split() would fail.

# np.split() works for arrays where we can split into equal parts.
# np.array_split() works with both equal and unequal length of elements.

Alpha-2025

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array_split(arr,2)
print(arr1)

print(type(arr1[0]))

[array([[1, 2, 3]]), array([[4, 5, 6]])]
<class 'numpy.ndarray'>


In [ ]:
# vsplit()
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.vsplit(arr,2)
print(arr1)


[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
# dsplit()
arr = np.array([[[1,4],
  [2,5],
  [3,6]]])

arr1 = np.dsplit(arr,2)
print(arr1)
print(arr1[0].shape)

[array([[[1],
        [2],
        [3]]]), array([[[4],
        [5],
        [6]]])]
(1, 3, 1)


In [29]:
# hsplit()
arr = np.array([[[1,4],
  [2,5],
  [3,6]]])

arr1 = np.hsplit(arr,3)
print(arr1)

[array([[[1, 4]]]), array([[[2, 5]]]), array([[[3, 6]]])]
