In [1]:
import numpy as np

In [3]:
arr = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ],
])
arr.shape

(3, 3, 3)

nditer()

In [3]:
# same as above nested for loops.
for i in np.nditer(arr[1]):
    print(i)

10
11
12
13
14
15
16
17
18


ndenumerate()

In [5]:
for i,j in np.ndenumerate(arr):
    print(i,':',j)

(0, 0, 0) : 1
(0, 0, 1) : 2
(0, 0, 2) : 3
(0, 1, 0) : 4
(0, 1, 1) : 5
(0, 1, 2) : 6
(0, 2, 0) : 7
(0, 2, 1) : 8
(0, 2, 2) : 9
(1, 0, 0) : 10
(1, 0, 1) : 11
(1, 0, 2) : 12
(1, 1, 0) : 13
(1, 1, 1) : 14
(1, 1, 2) : 15
(1, 2, 0) : 16
(1, 2, 1) : 17
(1, 2, 2) : 18
(2, 0, 0) : 19
(2, 0, 1) : 20
(2, 0, 2) : 21
(2, 1, 0) : 22
(2, 1, 1) : 23
(2, 1, 2) : 24
(2, 2, 0) : 25
(2, 2, 1) : 26
(2, 2, 2) : 27


In [8]:
arr = np.array([1,2,3,4,5,6])
for i,j in np.ndenumerate(arr):
    print(i,':',j)

(0,) : 1
(1,) : 2
(2,) : 3
(3,) : 4
(4,) : 5
(5,) : 6


In [14]:
arr = np.array(99)
for i,j in np.ndenumerate(arr):
    print(i,':',j)

() : 99


reshape()

In [ ]:
'''

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

'''

In [7]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = arr.reshape(4,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print('------reshaping into 2D array------')
arr1 = arr.reshape(6,2)
print(arr1)

arr1 = arr.reshape(2,6)
print(arr1)

arr1 = arr.reshape(12,1)
print(arr1)

arr1 = arr.reshape(4,3)
print(arr1)

------reshaping into 2D array------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
print('------reshaping into 3D array------')

arr1 = arr.reshape(2,2,3)
print(arr1)

arr1 = arr.reshape(3,2,2)
print(arr1)

------reshaping into 3D array------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Unknown dimension

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.reshape(3,2,-1))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1 = arr.reshape(2,-1,3)     # if you give multiple -1: can only specify one unknown dimension
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Flattening the array
arr = np.array([
                [
                    [ 1,  1],
                    [ 3,  4]
                ],
                [
                    [ 5,  6],
                    [ 7,  8]
                ],
                [
                    [ 9, 10],
                    [11, 12]
                ]
               ])
print(arr.reshape(-1))  # converts to 1D array

[ 1  1  3  4  5  6  7  8  9 10 11 12]


Alpha-2025

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr1 = arr.reshape(9,1)
print(arr1)

print('------------------------')
arr2 = arr.reshape(3,3)
print(arr2)

print('------------------------')
arr3 = arr.reshape(1,9,1)
print(arr3)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr4 = arr.reshape(3,3,1)
print(arr4)

print('--------------10-D--------------')
arr5 = arr.reshape(1,1,1,1,1,1,3,1,1,3)  # 10D
print(arr5)


[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
--------------10-D--------------
[[[[[[[[[[1 2 3]]]


       [[[4 5 6]]]


       [[[7 8 9]]]]]]]]]]


In [ ]:
# flattening array without using reshape function

arr = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

l = []
for i in np.nditer(arr):
    l.append(int(i))

print(type(l),l)

arr = np.array(l)
print(type(arr),arr)
arr

<class 'list'> [1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'> [1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])