In [1]:
import numpy as np

where()

In [ ]:
'''

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

'''

In [18]:
arr = np.array([1,2,3,67,5,67,8,9])
x = 67

for i,j in np.ndenumerate(arr):
    if j==x:
        print(i)


print(np.where(arr==x))

(3,)
(5,)
(array([3, 5], dtype=int64),)


In [11]:
arr = np.array([1,5,3,7,44,3,4,7])
arr1 = np.where(arr == 3)
print(arr1)

# when the element is not present in that array it will return a blanck array
arr2 = np.where(arr == 333)
print(arr2)

(array([2, 5]),)
(array([], dtype=int64),)


In [19]:
even = np.where(arr%2==0)
print(even)

odd = np.where(arr%2==1)
print(odd)

(array([1, 6], dtype=int64),)
(array([0, 2, 3, 4, 5, 7], dtype=int64),)


searchsorted()

In [ ]:
'''

Search Sorted:

There is a method called searchsorted() which performs a binary search in the array, 

and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

'''

In [5]:
arr = np.array([6,8,9])
x = np.searchsorted(arr,8)   # by default side='left'
print(x)

1


In [3]:
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,9,side='right')  
print(x)

4


In [ ]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,1])
print(x)

[1 2 0]


In [ ]:
arr = np.array([6,8,9,2])
x = np.searchsorted(arr,3)
print(x)

# If the array is not sorted it returns random indices

0


sort()

In [24]:
# arrange the elements in ordered sequence

arr = np.array([1,65,3,5,6,3,2])
print(np.sort(arr))

[ 1  2  3  3  5  6 65]


In [25]:
# decending order

arr = np.array([1,65,3,5,6,3,2])
print((np.sort(arr))[::-1])

[65  6  5  3  3  2  1]


In [26]:

arr = np.array(['apple','grapes','cherry'])
print(np.sort(arr))

['apple' 'cherry' 'grapes']


In [27]:

arr = np.array([[10,4,3],[5,0,1]])
print(np.sort(arr))

[[ 3  4 10]
 [ 0  1  5]]


In [ ]:
arr = np.array([[10,4,3],[5,0,1]])  # operates column wise
print(np.sort(arr,axis=0))

[[ 5  0  1]
 [10  4  3]]


Filter:

In [ ]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering

In [ ]:
# fetching values at index 0 and 2
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [6]:
arr = np.array([1,2,4,6,4,7,8])
f = arr>3
print(arr[f])

even = arr%2==0
print(arr[even])

print(even)

[4 6 4 7 8]
[2 4 6 4 8]
[False  True  True  True  True False  True]


Alpha-2025

In [ ]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering.

arr = np.array([41, 42, 43, 44])

# Find the element greater than 42

arr2 = np.where(arr>42)
for i in np.nditer(arr2):
    print(arr[i])


# using filtering

x = arr>42
arr1 = arr[x]
print(arr1)


43
44
[43 44]
