In [1]:
import numpy as np

Changes in arrays:

append()

In [5]:
# 1D
arr = np.array([1,2,3,4,5])
print(np.append(arr,6))

[1 2 3 4 5 6]


In [6]:
arr = np.array([1,2,3,4,5])
print(np.append(arr,[6,7]))  # passing multiple elements

[1 2 3 4 5 6 7]


In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.append(arr,[[7,8,9]],axis=0))  # column wise

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.append(arr,[[7],[8]],axis=1))  # row wise

[[1 2 3 7]
 [4 5 6 8]]


In [26]:
'''

i/p:
[
  [2,3],
  [4,5]
]

o/p:
[
  [2,3,7],
  [4,5,6],
  [10,11,12]
]

'''

arr = np.array([

                 [2,3],

                 [4,5]

               ])
arr = np.append(arr,[[7],[6]],axis=1)
arr = np.append(arr,[[10,11,12]],axis=0)
print(arr)

[[ 2  3  7]
 [ 4  5  6]
 [10 11 12]]


In [25]:
arr = np.array([

                 [2,3],

                 [4,5]

               ])

arr1 = np.append(arr,[[10],[11]],axis=1)
arr1 = np.append(arr1,[[10,11,12]],axis=0)
print(arr1)

[[ 2  3 10]
 [ 4  5 11]
 [10 11 12]]


In [ ]:
# Using concatenate
# PENDING
arr1 = np.array([

                 [2,3],

                 [4,5]

               ])
arr2 = np.array([[10],[11]])
arr = np.concatenate([arr1,arr2],axis=1)

arr3 = np.array([10,11,12])

print(arr)

[[ 2  3 10]
 [ 4  5 11]]


update array elements:

In [11]:
arr = np.array([1,2,3,4])
arr[1]=200
arr

array([  1, 200,   3,   4])

In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[1][1]=600
arr

array([[  1,   2,   3,   4],
       [  5, 600,   7,   8]])

delete

In [ ]:
arr = np.array([1,2,3,4])
arr = np.delete(arr,1)  # takes index of the corresponding element
arr

array([1, 3, 4])

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr = np.delete(arr,1,axis=0)   # row wise
arr

array([[1, 2, 3, 4]])

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr = np.delete(arr,1,axis=1)   # column wise
arr

array([[1, 3, 4],
       [5, 7, 8]])

insert()

In [46]:
# 1D
arr = np.arange(0,9)
print(arr)

arr1 = np.insert(arr,9,[9,10])  # insert(arr,index,value)
print(arr1)

print(np.insert(arr1,0,-1))

print(np.insert(arr,-1,[11,12]))

[0 1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7 11 12  8]


In [ ]:
# 2D
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]])


arr1 = np.insert(arr,arr[0][0],[11,12,13,14],axis=0)
print(arr1)

[[ 1  2  3  4]
 [11 12 13 14]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
arr = np.array([
    [1,2],
    [3,4]
])

print(np.insert(arr,arr[0][1],[[11,12]],axis=1))


[[ 1  2 11]
 [ 3  4 12]]


In [ ]:
x = np.empty((2,2)) # empty(): Creates an uninitialized array of a given shape.
x


array([[9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323]])

Alpha-2025

In [ ]:
# Insert into flattened array:
a = np.array([[1, 2], [3, 4]])
b = np.insert(a, 1, 99)
print(b)

[ 1 99  2  3  4]


In [3]:
# Insert row (axis = 0):
a = np.array([[1, 2], [3, 4]])
b = np.insert(a, 1, [9, 9], axis=0)
print(b)

[[1 2]
 [9 9]
 [3 4]]


In [4]:
#  Insert column (axis = 1):
a = np.array([[1, 2], [3, 4]])
b = np.insert(a, 1, [9, 9], axis=1)
print(b)

[[1 9 2]
 [3 9 4]]
