In [ ]:
# NumPy offers the random module to work with random numbers.
import numpy as np
from numpy import random

Random:

In [ ]:
# Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

randint()

In [12]:
x = random.randint(10)
x

4

In [33]:
x = random.randint(8,10)
x

9

random.rand()

In [84]:
# The random module's rand() method returns a random float between 0 and 1
x = random.rand()
x

0.7295511337938502

In [101]:
# The rand() method also allows you to specify the shape of the array.

print('--------Ex-1----------')
x = random.rand(3)
print(x)

print('--------Ex-2----------')
x = random.rand(3,4)
print(x)
x.shape

--------Ex-1----------
[0.20200126 0.89548992 0.76714138]
--------Ex-2----------
[[0.42638893 0.8788172  0.26953155 0.59483975]
 [0.34735466 0.80725767 0.62390839 0.15596675]
 [0.18293688 0.98504729 0.99878725 0.78267706]]


(3, 4)

In [92]:
# The randint() method takes a size parameter where you can specify the shape of an array.
x=random.randint(100, size=(10))
print(x)

[13 18 39 11 72 16 18 23 89 21]


In [96]:
x = random.randint(100, size=(3, 5))
print(x)
x.shape

[[60 82  2  7 98]
 [72  1 68 48 63]
 [16 28  4 95 85]]


(3, 5)

In [7]:
x = random.randint(10)
n=1
while n<=3:
    print(f'You have {4-n} attempts!!!')
    num = int(input("Enter a number: "))
    if x==num:
        print('You won the game.')
        break
    else:
        print('You lost the game.')
    n+=1

You have 3 attempts!!!
You lost the game.
You have 2 attempts!!!
You won the game.


Generate Random Number From Array:

In [70]:
# The choice() method allows you to generate a random value based on an array of values.
# The choice() method takes an array as a parameter and randomly returns one of the values.

x = random.choice([3, 5, 7, 9])
print(x)
x = random.choice([3, 5, 7, 9],9)
print(x)

3
[5 7 7 7 5 3 9 3 7]


In [72]:
# The choice() method also allows you to return an array of values.
# Add a size parameter to specify the shape of the array.

x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[5 9 3 9 9]
 [5 9 9 9 5]
 [3 7 3 7 5]]


Uniform Distribution:

In [ ]:
'''
Used to describe probability where every event has equal chances of occuring.
E.g. Generation of random numbers.
It has three parameters:
low - lower bound - default 0.0
high - upper bound - default 1.0
size - The shape of the returned array.

'''

In [57]:
x = random.uniform(1,3,5)  # uniform(low,high,size)
print(x)

[2.50331571 1.14607574 2.24769193 2.8588534  2.9783083 ]


In [118]:
x = random.uniform(size=(2, 3))
print(x)

[[0.26142747 0.33397519 0.62541342]
 [0.23327887 0.73971982 0.29249189]]


Shuffling Arrays:

In [74]:
# The shuffle() method makes changes to the original array.

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[5 1 4 3 2]


In [101]:
# Sampling

arr = np.array([1,2,3,4,5])
x = np.random.choice(arr,2)
print(x)

# Sample with replace
arr = np.array([1,2,3,4,5])
x = np.random.choice(arr,8,replace=True)  # defualt
print(x)

z = np.random.choice(arr,3,replace=False)  # elements repitation not allowed
print(z)

l = [1,2.3,'abc']
k = np.random.choice(l,1)
print(k,type(k))

[2 2]
[3 5 5 5 5 2 3 1]
[1 3 5]
['1'] <class 'numpy.ndarray'>
